include:
  - local: 'ci-files/validate.yml'
  - local: 'ci-files/test.yml'
  - local: 'ci-files/plan.yml'
  - local: 'ci-files/deploy.yml'
  - local: 'ci-files/apply.yml'

stages:
  - validate
  - test
  - plan
  - deploy
  - apply